### ISSUE TITLE
Not sure how to install this

### ISSUE THREAD

**Issue by DenLilleMand** [hyhugh/coc-erlang_ls#1]
When i run `:CocInstall coc-erlang_ls` it just gives a `[coc.nvim] Error on install coc-erlang_ls: Error: Invalid response from https://registry.npmjs.org/coc-erlang_ls: 404`. So i guess it isn't meant to be supported through npm. 

I have cloned  `erlang_ls` and ran some rebar3 commands like they said. I added some stuff to my CocConfig so it looks like this:
```
{
    "languageserver": {
       //... other language servers
    },
    "python.jediEnabled": false,
    "erlang_ls.erlang_ls_path": "/home/denlillemand/erlang_ls/",
    "erlang_ls.port": 155900,
    "erlang_ls.trace.server": "verbose"
}
```
When i open a .erl file i get smt like this:
```
... at LanguageClient.resolveConnection (/home/denlillemand/.config/nvim/plugged/coc.nvim/lib/language-client/client.
js:1968:44)
```
I copied a `erlang_ls` executable into my path, didn't change anything.

I am not sure what to do ? it is also the first time i am developing with Erlang, I don't really understand all of this rebar stuff.

**Comment by hyhugh** [comment]
Hi there,

Sorry I didn't push `coc-erlang_ls` onto `npm`.
and `CocInstall` uses `npm install blah`(or it's yarn equivalent) to install coc plugin.

So to install this plugin please use your vim plugin manager(vim-plug or something equivalent). The instructions are available in the `readme` file.

**Comment by DenLilleMand** [comment]
Yeah i already installed it with that method, it just gives me this error:
```
... at LanguageClient.resolveConnection (/home/denlillemand/.config/nvim/plugged/coc.nvim/lib/language-client/client.
js:1968:44)
```
When i open a erl file, i think it is related to me not having installed erlang_ls properly, i did run its installation instructions though. I am unsure if this plugin is suppose to start the erl language server, or if i should start it my self, and how to specify the port of the LS, the binary takes a integer argument, but that isn't the port.

**Comment by hyhugh** [comment]
normally the plugin should be able to start the language server automatically. I'm not sure what's happening. could you post your `:CocInfo` output in vim?

**Comment by DenLilleMand** [comment]
```
## versions

vim version: NVIM v0.4.2
node version: v12.13.0
coc.nvim version: 0.0.74
term: xterm-256color
platform: linux

## Messages
[coc.nvim] error: UnhandledRejection: Port should be >= 0 and < 65536. Received 155900.
RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 155900.
    at lookupAndConnect (net.js:988:13)
    at Socket.connect (net.js:963:5)
    at Object.connect (net.js:172:17)
    at Object.waitForSocket (/home/denlillemand/.config/nvim/plugged/coc-erlang_ls/lib/index.js:465:20)
    at /home/denlillemand/.config/nvim/plugged/coc-erlang_ls/lib/index.js:105:36
    at new Promise (<anonymous>)
    at /home/denlillemand/.config/nvim/plugged/coc-erlang_ls/lib/index.js:104:16
    at LanguageClient.createMessageTransports (/home/denlillemand/.config/nvim/plugged/coc.nvim/lib/language-client/index.js:195:48)
    at LanguageClient.createConnection (/home/denlillemand/.config/nvim/plugged/coc.nvim/lib/language-client/client.js:2186:21)
    at LanguageClient.resolveConnection (/home/denlillemand/.config/nvim/plugged/coc.nvim/lib/language-client/client.js:1968:44)
## Output channel: coc-erlang

waiting for erlang_ls to accept connection..

## Output channel: erlang_ls

[Error  - 10:27:51 AM] Starting client failed: 
RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 155900.
    at lookupAndConnect (net.js:988:13)
    at Socket.connect (net.js:963:5)
    at Object.connect (net.js:172:17)
    at Object.waitForSocket (/home/denlillemand/.config/nvim/plugged/coc-erlang_ls/lib/index.js:465:20)
    at /home/denlillemand/.config/nvim/plugged/coc-erlang_ls/lib/index.js:105:36
    at new Promise (<anonymous>)
    at /home/denlillemand/.config/nvim/plugged/coc-erlang_ls/lib/index.js:104:16
    at LanguageClient.createMessageTransports (/home/denlillemand/.config/nvim/plugged/coc.nvim/lib/language-client/index.js:195:48)
    at LanguageClient.createConnection (/home/denlillemand/.config/nvim/plugged/coc.nvim/lib/language-client/client.js:2186:21)
    at LanguageClient.resolveConnection (/home/denlillemand/.config/nvim/plugged/coc.nvim/lib/language-client/client.js:1968:44)


```

**Comment by hyhugh** [comment]
yeah the error message says your port should be >= 0 and < 65536.
and the port `155900` in your config is not allowed by coc.

**Comment by hyhugh** [comment]
@DenLilleMand any updates?

**Comment by DenLilleMand** [comment]
> @DenLilleMand any updates?

Yeah, I changed the port to something sensible and now it just says:
```
## versions

vim version: NVIM v0.4.2
node version: v12.13.0
coc.nvim version: 0.0.74
term: xterm-256color
platform: linux

## Messages

## Output channel: coc-erlang

waiting for erlang_ls to accept connection..
```

But I was trying to install it for an exam that has erlang in it, which I am in the middle of now so I don't really have time to spend on this until after friday. Thanks for asking though !

**Comment by robertoaloi** [comment]
@hyhugh Just discovered your extension. Thanks! Do you think you could contribute a section on how to set it up in https://github.com/erlang-ls/erlang_ls/blob/master/README.md ? That would help nvim users tremendously.

**Comment by hyhugh** [comment]
> @hyhugh Just discovered your extension. Thanks! Do you think you could contribute a section on how to set it up in https://github.com/erlang-ls/erlang_ls/blob/master/README.md ? That would help nvim users tremendously.

Hi,
Thanks for creating a great language server!
But I'm really busy recently, I'll get back to you and PR when free.

**Comment by robertoaloi** [comment]
Sounds good to me. Have fun with whatever you are building! :)

**Comment by robertoaloi** [comment]
@hyhugh A contributor kindly provided the instructions already:

https://github.com/erlang-ls/erlang_ls/pull/262

Feel free to have a look at the instructions when you have time again and let us know if anything is incorrect or missing.

**Comment by matlapo** [comment]
@hyhugh I followed the readme and it doesn't work for me. My coc config is:
```
{
  "erlang_ls.port": 5352,
  "erlang_ls.erlang_ls_path": "/Users/m1.lapointe/Projects/erlang_ls/_build/default/bin/erlang_ls",
  "erlang_ls.trace.server": "verbose"
}
```
and `:CocInfo`:
```
## versions

vim version: NVIM v0.4.3
node version: v13.8.0
coc.nvim version: 0.0.74-6700e7468d
term: iTerm.app
platform: darwin

## Messages
```

Any idea? Coc should start `erlang_ls` automatically so I don't see why nothing happens.

**Comment by robertoaloi** [comment]
@liamjjmcnamara Something that you could help with?

**Comment by liamjjmcnamara** [comment]
I start erlang_ls manually rather than through vim. @matlapo do things work when you do that? i.e. is your issue just a start issue?

**Comment by hyhugh** [comment]
Hi, the plugin has been updated, it now uses stdio to communicate with `erlang_ls`, which should fix some strange issues related to TCP.
can you guys try again to check if any issue still remains? The plugin now should be able to start erlang_ls itself.

**Comment by DenLilleMand** [comment]
I still can't run it. I updated `Neovim`, `erlang-ls/erlang_ls`, and updated this plugin. 

If i run `./erlang_ls/_build/default/bin/erlang_ls 19527 ` on my machine, erlang_ls starts the process and listens on that port.

But when i start Nvim on a .erl file i get: `[coc.nvim] The "erlang_ls" server crashed 5 times in the last 3 minutes. The server will not be restarted.`

My config looks like this now:
```
    "erlang_ls.erlang_ls_path": "/home/denlillemand/erlang_ls/_build/default/bin/erlang_ls",
    "erlang_ls.trace.server": "verbose"
```
I also tried specifying the port, but no change, the erlang_ls server is never started.
I also tried to install the `coc-erlang_ls` package again, i guess you put it on NPM now, but it makes no difference.

My `~/.config/erlang_ls` file just contains:
```
otp_path: "/usr/lib/erlang"
```
Not sure if i need to fill out more information to configure Erlang_ls to just get a minimal thing going, the path to otp is correct at least. 

I get this output with verbose and `:CocInfo`, if it is any help(It does this 5 times, same result every time):
```
## Output channel: erlang_ls

[Trace - 2:23:10 AM] Sending request 'initialize - (0)'.
Params: {
    "processId": 18789,
    "rootPath": "/home/denlillemand/elixir",
    "rootUri": "file:///home/denlillemand/elixir",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                }
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true,
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "declaration": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            }
        },
        "window": {
            "workDoneProgress": true
        }
    },
    "initializationOptions": "",
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///home/denlillemand/elixir",
            "name": "elixir"
        }
    ],
    "clientInfo": {
        "name": "coc.nvim",
        "version": "0.0.78"
    }
}


[Error  - 2:23:10 AM] /home/denlillemand/erlang_ls/_build/default/bin/erlang_ls exited with code: 127
[Info  - 2:23:10 AM] Connection to server got closed. Server will restart.
```

**Comment by robertoaloi** [comment]
Hi @DenLilleMand 

I assumed you followed the guide at:

https://erlang-ls.github.io/editors/vim/

Do the server-side logs show anything interesting? Here are some info on where you can find the server-side logs:

https://erlang-ls.github.io/troubleshooting/

**Comment by DenLilleMand** [comment]
If i run:
```
./erlang_ls/_build/default/bin/erlang_ls 19527
```
And then i run 
```
epmd -port 19527 -names
```
It doesn't halt, but does not exit either.
If i just try to run `epmd -names` it just says: "epmd: Cannot connect to local epmd"
so i can't connect to the debugging session as they say with:
`erl -sname debug -remsh erlang_ls_62880311918@`HOSTNAME``
Because i can't get the name of the server.

Like, i am not a genius at language servers or anything, maybe this feature is made for a little more advanced users hehe. Also, the language server seems to run just fine when i run it manually, i guess the interesting part would be to hook into a verbose log of what the erlang_ls server says when this plugin tries to start it.

So i tried to run e.g.
```
./erlang_ls/_build/default/bin/erlang_ls --log-level debug 19527
```
and 
```
./erlang_ls/_build/default/bin/erlang_ls --log-level=debug 19527
```
But the `--log-level` is not recognized as a argument, so not sure what this arg is for, if it is for the `erl` command when you have the host name.
i created the `.cache/erlang_ls` directory, that is the output of my `filename:basedir(user_log, "erlang_ls").`, but there is no `log` file in that directory, i thought maybe that would be a way to check the output. 

Can you see if i have something unattempted?

**Comment by robertoaloi** [comment]
The `port` parameter for `epmd` is used to configure Erlang Port Mapper Daemon, not something we are interested here. Simply:

`epmd  -names`

Should work. May I suggest you start with a clean slate:

```
killall beam.smp
killall epmd
```

**Comment by DenLilleMand** [comment]
> The `port` parameter for `epmd` is used to configure Erlang Port Mapper Daemon, not something we are interested here. Simply:
> 
> `epmd -names`
> 
> Should work. May I suggest you start with a clean slate:
> 
> ```
> killall beam.smp
> killall epmd
> ```

Maybe i am a little confused now, i ran:
```
epmd -port 4369 -debug
```
And it started the epmd server or whatever, and then running `epmd -names` in another terminal gives me just a empty list, even though `~/erlang_ls/_build/default/bin/erlang_ls 19527` is running in another terminal.

**Comment by robertoaloi** [comment]
Uhm, let's start from the basics. Can you start an Erlang node in distributed mode?

```
erl -sname test
```

**Comment by hyhugh** [comment]
> I still can't run it. I updated `Neovim`, `erlang-ls/erlang_ls`, and updated this plugin.
> 
> If i run `./erlang_ls/_build/default/bin/erlang_ls 19527 ` on my machine, erlang_ls starts the process and listens on that port.
> 
> But when i start Nvim on a .erl file i get: `[coc.nvim] The "erlang_ls" server crashed 5 times in the last 3 minutes. The server will not be restarted.`
> 
> My config looks like this now:
> 
> ```
>     "erlang_ls.erlang_ls_path": "/home/denlillemand/erlang_ls/_build/default/bin/erlang_ls",
>     "erlang_ls.trace.server": "verbose"
> ```
> 
> I also tried specifying the port, but no change, the erlang_ls server is never started.
> I also tried to install the `coc-erlang_ls` package again, i guess you put it on NPM now, but it makes no difference.
> 
> My `~/.config/erlang_ls` file just contains:
> 
> ```
> otp_path: "/usr/lib/erlang"
> ```
> 
> Not sure if i need to fill out more information to configure Erlang_ls to just get a minimal thing going, the path to otp is correct at least.
> 
> I get this output with verbose and `:CocInfo`, if it is any help(It does this 5 times, same result every time):
> 
> ```
> ## Output channel: erlang_ls
> 
> [Trace - 2:23:10 AM] Sending request 'initialize - (0)'.
> Params: {
>     "processId": 18789,
>     "rootPath": "/home/denlillemand/elixir",
>     "rootUri": "file:///home/denlillemand/elixir",
>     "capabilities": {
>         "workspace": {
>             "applyEdit": true,
>             "workspaceEdit": {
>                 "documentChanges": true,
>                 "resourceOperations": [
>                     "create",
>                     "rename",
>                     "delete"
>                 ],
>                 "failureHandling": "textOnlyTransactional"
>             },
>             "didChangeConfiguration": {
>                 "dynamicRegistration": true
>             },
>             "didChangeWatchedFiles": {
>                 "dynamicRegistration": true
>             },
>             "symbol": {
>                 "dynamicRegistration": true,
>                 "symbolKind": {
>                     "valueSet": [
>                         1,
>                         2,
>                         3,
>                         4,
>                         5,
>                         6,
>                         7,
>                         8,
>                         9,
>                         10,
>                         11,
>                         12,
>                         13,
>                         14,
>                         15,
>                         16,
>                         17,
>                         18,
>                         19,
>                         20,
>                         21,
>                         22,
>                         23,
>                         24,
>                         25,
>                         26
>                     ]
>                 },
>                 "tagSupport": {
>                     "valueSet": [
>                         1
>                     ]
>                 }
>             },
>             "executeCommand": {
>                 "dynamicRegistration": true
>             },
>             "configuration": true,
>             "workspaceFolders": true
>         },
>         "textDocument": {
>             "publishDiagnostics": {
>                 "relatedInformation": true,
>                 "versionSupport": false,
>                 "tagSupport": {
>                     "valueSet": [
>                         1,
>                         2
>                     ]
>                 }
>             },
>             "synchronization": {
>                 "dynamicRegistration": true,
>                 "willSave": true,
>                 "willSaveWaitUntil": true,
>                 "didSave": true
>             },
>             "completion": {
>                 "dynamicRegistration": true,
>                 "contextSupport": true,
>                 "completionItem": {
>                     "snippetSupport": true,
>                     "commitCharactersSupport": true,
>                     "documentationFormat": [
>                         "markdown",
>                         "plaintext"
>                     ],
>                     "deprecatedSupport": true,
>                     "preselectSupport": true
>                 },
>                 "completionItemKind": {
>                     "valueSet": [
>                         1,
>                         2,
>                         3,
>                         4,
>                         5,
>                         6,
>                         7,
>                         8,
>                         9,
>                         10,
>                         11,
>                         12,
>                         13,
>                         14,
>                         15,
>                         16,
>                         17,
>                         18,
>                         19,
>                         20,
>                         21,
>                         22,
>                         23,
>                         24,
>                         25
>                     ]
>                 }
>             },
>             "hover": {
>                 "dynamicRegistration": true,
>                 "contentFormat": [
>                     "markdown",
>                     "plaintext"
>                 ]
>             },
>             "signatureHelp": {
>                 "dynamicRegistration": true,
>                 "signatureInformation": {
>                     "documentationFormat": [
>                         "markdown",
>                         "plaintext"
>                     ],
>                     "parameterInformation": {
>                         "labelOffsetSupport": true
>                     }
>                 }
>             },
>             "definition": {
>                 "dynamicRegistration": true
>             },
>             "references": {
>                 "dynamicRegistration": true
>             },
>             "documentHighlight": {
>                 "dynamicRegistration": true
>             },
>             "documentSymbol": {
>                 "dynamicRegistration": true,
>                 "symbolKind": {
>                     "valueSet": [
>                         1,
>                         2,
>                         3,
>                         4,
>                         5,
>                         6,
>                         7,
>                         8,
>                         9,
>                         10,
>                         11,
>                         12,
>                         13,
>                         14,
>                         15,
>                         16,
>                         17,
>                         18,
>                         19,
>                         20,
>                         21,
>                         22,
>                         23,
>                         24,
>                         25,
>                         26
>                     ]
>                 },
>                 "hierarchicalDocumentSymbolSupport": true,
>                 "tagSupport": {
>                     "valueSet": [
>                         1
>                     ]
>                 }
>             },
>             "codeAction": {
>                 "dynamicRegistration": true,
>                 "isPreferredSupport": true,
>                 "codeActionLiteralSupport": {
>                     "codeActionKind": {
>                         "valueSet": [
>                             "",
>                             "quickfix",
>                             "refactor",
>                             "refactor.extract",
>                             "refactor.inline",
>                             "refactor.rewrite",
>                             "source",
>                             "source.organizeImports"
>                         ]
>                     }
>                 }
>             },
>             "codeLens": {
>                 "dynamicRegistration": true
>             },
>             "formatting": {
>                 "dynamicRegistration": true
>             },
>             "rangeFormatting": {
>                 "dynamicRegistration": true
>             },
>             "onTypeFormatting": {
>                 "dynamicRegistration": true
>             },
>             "rename": {
>                 "dynamicRegistration": true,
>                 "prepareSupport": true
>             },
>             "documentLink": {
>                 "dynamicRegistration": true,
>                 "tooltipSupport": true
>             },
>             "typeDefinition": {
>                 "dynamicRegistration": true
>             },
>             "implementation": {
>                 "dynamicRegistration": true
>             },
>             "declaration": {
>                 "dynamicRegistration": true
>             },
>             "colorProvider": {
>                 "dynamicRegistration": true
>             },
>             "foldingRange": {
>                 "dynamicRegistration": true,
>                 "rangeLimit": 5000,
>                 "lineFoldingOnly": true
>             },
>             "selectionRange": {
>                 "dynamicRegistration": true
>             }
>         },
>         "window": {
>             "workDoneProgress": true
>         }
>     },
>     "initializationOptions": "",
>     "trace": "verbose",
>     "workspaceFolders": [
>         {
>             "uri": "file:///home/denlillemand/elixir",
>             "name": "elixir"
>         }
>     ],
>     "clientInfo": {
>         "name": "coc.nvim",
>         "version": "0.0.78"
>     }
> }
> 
> 
> [Error  - 2:23:10 AM] /home/denlillemand/erlang_ls/_build/default/bin/erlang_ls exited with code: 127
> [Info  - 2:23:10 AM] Connection to server got closed. Server will restart.
> ```

Hi, currently this plugin uses `stdio` to communicate with `erlang_ls`, and you shouldn't worry about the tcp socket number thingy anymore. although i nolonger work on any erlang based projects, I will test this plugin later today and get back to you soon.
